baseURL = 'http://tmedocs.arubacorp.net/'
languageCode = 'en-us'
title = 'TechDocs - WLAN, SD-Branch, & Location Services'
theme = 'docsy'


enableRobotsTXT = true
enableGitInfo = true

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"


[outputs]
section = ["HTML", "print"]

[[menu.main]]
  name = "HPE Networking Support Portal"
  weight = 30
  url = "https://networkingsupport.hpe.com/"
[[menu.main]]
  name = "Documentation Portal"
  weight = 50
  url = "https://www.arubanetworks.com/techdocs/ArubaDocPortal/content/docportal.htm"

[params]
offlineSearch = true

copyright = 'Hewlett Packard Enterprise Development LP'


# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to false to disable the About link in the site footer
footer_about_enable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Menu depth to show by default
ul_show = 1
# Enable to let users expand and collapse menu sections.
sidebar_menu_foldable = true
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false

# -------------------------
# Modifed from default
# Adds a section called "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
#yes = 'Glad to hear it! Please tell us how we can improve.'
#no = 'Sorry to hear that. Please tell us how we can improve.'
yes = 'Glad to hear it!'
no = 'Sorry to hear that.'
# Send feedback by email information
feedback_enable_email = true
feedback_prompt = 'Please let us know how we can improve.'
feedback_email = 'aruba-tme-feedback@hpe.com'


# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = true

# By default, Docsy shows the table of contents for the current page in the right sidebar using the built-in function of Hugo.
# Replace that with a JavaScript-based ToC that uses the [https://tscanlin.github.io/tocbot/](Tocbot library) by setting enable to true
# By default, h2-h4 headings are included in the sidebar, which includes tips and warnings if using the alert shortcode of Docsy
# Change the included headings by specifying a comma-separated list in custom_headings.
[params.jstoc]
enable = true
custom_headings = "h1, h2, h3, h4, h5, h6"
# ignore_selector = ""
collapse_depth = 3

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.

[[params.links.user]]
#  name = "Site Feedback"
#  url = "mailto:"
#  icon = "fa fa-envelope"
#  desc = "Discussion and help from your fellow users"

[params.mermaid]
theme = "base"

[params.mermaid.themevariables]
darkMode = false
background = "#fff"
fontFamily = "Open Source Pro, arial"
textColor = "#000"
primaryColor = "#ff8300"
primaryBorderColor = "#ff8300"
primaryTextColor = "#fff"
secondaryColor = "#01A982"
tertiaryColor = "#7FF9E2"
noteBkgColor = "#f6f6f6"
noteTextColor = "#000"


[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    #path = "/Users/mgeorge/Documents/TME-Docs/hugo-tmedocs/quickstart/docsy"
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
  [[module.imports]]
    #path = "/Users/mgeorge/Documents/TME-Docs/hugo-tmedocs/quickstart/themes/twbs/bootstrap"
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[security.funcs]
getenv = ['^HUGO_', '^CI$','^NETLIFY$']
